---
#
# Compile and build iRODS microservices and policy as debian packages
# using Docker image in dockerfile/Dockerfile
#
# Usage:
#   docker-compose up
#
version: '2.4'

x-common: &common
  build:
    context: ./dockerfile
    args:
      # Must be available at
      # https://packages.irods.org/apt/dists/xenial/main/binary-amd64/Packages 
      # https://packages.irods.org/apt/dists/bionic/main/binary-amd64/Packages
      # IRODS_VERSION must match definition in microservices/CMakeList.txt
      IRODS_VERSION: 4.2.6
      CLANG_VERSION: 3.8
  volumes:
    - ./:/src
  command: "bash -x -c 'cmake . && make package'"
  
services:
  microservices:
    working_dir: /src/microservices
    <<: *common
  policy:
    working_dir: /src/policy
    <<: *common

